# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Services"
  #pageRef = "advisory"
  weight = 20

[[main]]
  name = "Advisory"
  parent = "Services"
  pageRef = "advisory"
  weight = 21

[[main]]
  name = "Speaking"
  parent = "Services"
  pageRef = "speaker"
  weight = 22

[[main]]
  name = "Insights"
  #pageRef = "articles"
  weight = 30

[[main]]
  name = "Articles"
  parent = "Insights"
  pageRef = "articles"
  weight = 31

[[main]]
  name = "Media"
  parent = "Insights"
  pageRef = "videos"
  weight = 32

[[main]]
  name = "Signals"
  parent = "Insights"
  pageRef = "signals"
  weight = 33

[[main]]
  name = "Engine Room"
  parent = "Insights"
  pageRef = "lab"
  weight = 34

[[main]]
  name = "Portfolio"
  pageRef = "portfolio"
  weight = 40

[[main]]
  name = "Contact"
  identifier = "contact-button"
  pageRef = "contact"
  weight = 50

[[main]]
  identifier = "X"
  pre = "x-twitter"
  url = "https://x.com/johnjanuszczak"
  weight = 60

[[main]]
  identifier = "LinkedIn"
  pre = "linkedin"
  url = "https://linkedin.com/in/johnjanuszczak"
  weight = 70

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Research"
  pageRef = "research"
  weight = 10

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
